CREATE TABLE `lexart_cube`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idLead` INT NOT NULL,
  `team` LONGTEXT NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

ALTER TABLE `teams` ADD `mainStack` LONGTEXT NULL DEFAULT NULL AFTER `name`;
