CREATE TABLE `lexart_cube`.`developer_origins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idDev` INT NOT NULL,
  `plataform` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
