ALTER TABLE user_skills_per_position DROP FOREIGN KEY user_skills_per_position_ibfk_2;
ALTER TABLE user_skills_per_position DROP FOREIGN KEY user_skills_per_position_ibfk_1;
ALTER TABLE user_skills_per_position DROP PRIMARY KEY;
UPDATE user_skills_per_position AS n INNER JOIN users  AS u ON u.idLextracking = n.idUser SET n.idUser = u.id;
ALTER TABLE user_skills_per_position ADD PRIMARY KEY (idUser, idPosition);
ALTER TABLE user_skills_per_position ADD FOREIGN KEY (idUser) REFERENCES users(id);
ALTER TABLE user_skills_per_position ADD FOREIGN KEY (idPosition) REFERENCES user_position_level(id);
UPDATE user_position_level AS n INNER JOIN users  AS u ON u.idLextracking = n.idUser SET n.idUser = u.id;
DELETE FROM user_skills WHERE idUser = 36;
ALTER TABLE user_skills DROP PRIMARY KEY;
UPDATE user_skills AS n INNER JOIN users AS u ON u.idLextracking = n.idUser SET n.idUser = u.id;
ALTER TABLE user_skills ADD PRIMARY KEY (idUser, idTechnology);
UPDATE users AS n INNER JOIN users AS u ON u.idLextracking = n.idUser SET n.idUser = u.id;
UPDATE evaluations AS n INNER JOIN users AS u ON u.idLextracking = n.idLextracking SET n.idLextracking = u.id;
UPDATE evaluations AS n INNER JOIN users AS u ON u.idLextracking = n.idUser SET n.idUser = u.id;
ALTER TABLE lead_dev_logs DROP PRIMARY KEY;
UPDATE lead_dev_logs AS n INNER JOIN users AS u ON u.idLextracking = n.idDev SET n.idDev = u.id;
UPDATE lead_dev_logs AS n INNER JOIN users  AS u ON u.idLextracking = n.idLead SET n.idLead = u.id;
ALTER TABLE lead_dev_logs ADD PRIMARY KEY(idDev, idLead);
